/*
  Warnings:

  - You are about to drop the column `categories` on the `jobs` table. All the data in the column will be lost.

*/
-- AlterSequence
ALTER SEQUENCE "jobs_id_seq" MAXVALUE 9223372036854775807;

-- AlterTable
ALTER TABLE "jobs" DROP COLUMN "categories";

-- CreateTable
CREATE TABLE "Category" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_JobCategories" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");

-- CreateIndex
CREATE UNIQUE INDEX "_JobCategories_AB_unique" ON "_JobCategories"("A", "B");

-- CreateIndex
CREATE INDEX "_JobCategories_B_index" ON "_JobCategories"("B");

-- AddForeignKey
ALTER TABLE "_JobCategories" ADD CONSTRAINT "_JobCategories_A_fkey" FOREIGN KEY ("A") REFERENCES "Category"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_JobCategories" ADD CONSTRAINT "_JobCategories_B_fkey" FOREIGN KEY ("B") REFERENCES "jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
