import { AnchorProvider, Program, Wallet } from "@coral-xyz/anchor";
import { Connection, PublicKey } from "@solana/web3.js";
import { HorseRace } from "./utils";
export * from "./instructions/admin";
export * from "./states";
export * from "./utils";
export declare const IDL: HorseRace;
export declare const HORSE_RACE_PROGRAM_ID: PublicKey;
export declare function getProgram(provider: AnchorProvider): Program<HorseRace>;
export declare function createProvider(connection: Connection, wallet: Wallet): AnchorProvider;
