-- AlterSequence
ALTER SEQUENCE "connection_requests_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "connections_id_seq" MAXVALUE 9223372036854775807;

-- AlterSequence
ALTER SEQUENCE "recent_searches_id_seq" MAXVALUE 9223372036854775807;

-- CreateTable
CREATE TABLE "follows" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "followerId" INT4 NOT NULL,
    "followedId" INT4 NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "follows_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "follows_followerId_followedId_key" ON "follows"("followerId", "followedId");

-- AddForeignKey
ALTER TABLE "follows" ADD CONSTRAINT "follows_followerId_fkey" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follows" ADD CONSTRAINT "follows_followedId_fkey" FOREIGN KEY ("followedId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
